url: "https://gracar.org"
baseurl: ""
title: "Peter Gracar"
description: "Probability, random geometric graphs, dependent percolation, and related stochastic processes."
author: "Peter Gracar"

collections:
  publications:
    output: false
  coauthors:
    output: false
  talks:
    output: false
  modules:
    output: false
  mini_cv:
    output: false

exclude:
  - CONTENT_GUIDE.md
