// swift-tools-version: 6.0

// WARNING:
// This file is automatically generated.
// Do not edit it by hand because the contents will be replaced.

import PackageDescription
import AppleProductTypes

let package = Package(
    name: "Lévy vs Brownian",
    platforms: [
        .iOS("26.0")
    ],
    products: [
        .iOSApplication(
            name: "Lévy vs Brownian",
            targets: ["AppModule"],
            bundleIdentifier: "org.gracar.LevyVsBrownian",
            displayVersion: "1.0",
            bundleVersion: "1",
            appIcon: .placeholder(icon: .barChart),
            accentColor: .presetColor(.indigo),
            supportedDeviceFamilies: [
                .pad,
                .phone
            ],
            supportedInterfaceOrientations: [
                .portrait,
                .landscapeRight,
                .landscapeLeft,
                .portraitUpsideDown(.when(deviceFamilies: [.pad]))
            ],
            appCategory: .education
        )
    ],
    targets: [
        .executableTarget(
            name: "AppModule",
            path: ".",
            swiftSettings: [
                // Swift Playgrounds always builds the debug configuration, so
                // force optimisation unconditionally for release-level perf.
                .unsafeFlags(["-O", "-whole-module-optimization"]),
            ]
        )
    ]
)
